services:
  - type: web
    name: ct-django-soft-dash-pro-live
    plan: starter
    env: python
    region: frankfurt  # region should be same as your database region.
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: "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"
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
